export type {
  CapacityError,
  CapacityPolicy,
  CapacityStatus,
  CoreError,
  CoreErrorCode,
  CoreResult,
  ExclusiveLockPort,
  FinalizationTicket,
  LocalDataPolicy,
  LockError,
  ReplacementAssessmentTicket,
  ReplacementCommitInput,
  ReplacementCommitResult,
  ReplacementMode,
  RequestRecord,
  RootReplacementPort,
  StorageError,
  StorageErrorCode,
  StoragePort,
  TransactionCommand,
  TransactionPort,
  TransactionReceipt,
} from "./contracts.js";

export { createFencingPolicy } from "./fencing.js";
export type {
  AcquireFenceInput,
  Fence,
  FenceCompletion,
  FenceControlState,
  FenceKind,
  FenceTransition,
  FencingPolicy,
  FencingProjection,
} from "./fencing.js";
